# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Project_TA\GrpTools\dcc\common\max\maxscript\scripts\Python\GrpPython\selecton\edit_ui.ui'
#
# Created: Thu Jul  5 12:11:54 2018
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.resize(465, 543)
        self.centralwidget = QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QSize(0, 52))
        self.groupBox_2.setMaximumSize(QSize(16777215, 52))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_8 = QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.bgImgPath = QLineEdit(self.groupBox_2)
        self.bgImgPath.setObjectName("bgImgPath")
        self.horizontalLayout_8.addWidget(self.bgImgPath)
        self.bgImgBt = QToolButton(self.groupBox_2)
        self.bgImgBt.setObjectName("bgImgBt")
        self.horizontalLayout_8.addWidget(self.bgImgBt)
        self.gridLayout.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QSize(0, 180))
        self.groupBox.setMaximumSize(QSize(16777215, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.msRb = QRadioButton(self.groupBox)
        self.msRb.setChecked(True)
        self.msRb.setObjectName("msRb")
        self.horizontalLayout_5.addWidget(self.msRb)
        self.pyRb = QRadioButton(self.groupBox)
        self.pyRb.setObjectName("pyRb")
        self.horizontalLayout_5.addWidget(self.pyRb)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.scriptSource = QTextEdit(self.groupBox)
        self.scriptSource.setObjectName("scriptSource")
        self.verticalLayout_3.addWidget(self.scriptSource)
        self.testRunBt = QPushButton(self.groupBox)
        self.testRunBt.setObjectName("testRunBt")
        self.verticalLayout_3.addWidget(self.testRunBt)
        self.gridLayout.addWidget(self.groupBox, 5, 0, 1, 1)
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btStats = QGroupBox(self.centralwidget)
        self.btStats.setMinimumSize(QSize(0, 120))
        self.btStats.setMaximumSize(QSize(280, 240))
        self.btStats.setObjectName("btStats")
        self.verticalLayout_4 = QVBoxLayout(self.btStats)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_10 = QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_3 = QLabel(self.btStats)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_10.addWidget(self.label_3)
        self.btTxt = QLineEdit(self.btStats)
        self.btTxt.setObjectName("btTxt")
        self.horizontalLayout_10.addWidget(self.btTxt)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QLabel(self.btStats)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.btX = QSpinBox(self.btStats)
        self.btX.setMaximum(2048)
        self.btX.setObjectName("btX")
        self.horizontalLayout_3.addWidget(self.btX)
        self.label_5 = QLabel(self.btStats)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.btY = QSpinBox(self.btStats)
        self.btY.setMaximum(2048)
        self.btY.setObjectName("btY")
        self.horizontalLayout_3.addWidget(self.btY)
        self.label_6 = QLabel(self.btStats)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.btW = QSpinBox(self.btStats)
        self.btW.setMinimum(2)
        self.btW.setMaximum(2048)
        self.btW.setObjectName("btW")
        self.horizontalLayout_3.addWidget(self.btW)
        self.label_7 = QLabel(self.btStats)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.btH = QSpinBox(self.btStats)
        self.btH.setMinimum(2)
        self.btH.setMaximum(2048)
        self.btH.setObjectName("btH")
        self.horizontalLayout_3.addWidget(self.btH)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_11 = QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.coloCb = QCheckBox(self.btStats)
        self.coloCb.setMaximumSize(QSize(18, 16777215))
        self.coloCb.setText("")
        self.coloCb.setObjectName("coloCb")
        self.horizontalLayout_11.addWidget(self.coloCb)
        self.colLbl = QLabel(self.btStats)
        self.colLbl.setMinimumSize(QSize(0, 0))
        self.colLbl.setObjectName("colLbl")
        self.horizontalLayout_11.addWidget(self.colLbl)
        self.label_8 = QLabel(self.btStats)
        self.label_8.setMaximumSize(QSize(36, 16777215))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_11.addWidget(self.label_8)
        self.alpha_2 = QSpinBox(self.btStats)
        self.alpha_2.setMaximumSize(QSize(48, 16777215))
        self.alpha_2.setMaximum(255)
        self.alpha_2.setProperty("value", 255)
        self.alpha_2.setObjectName("alpha_2")
        self.horizontalLayout_11.addWidget(self.alpha_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        spacerItem = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_4.addWidget(self.btStats)
        self.selObjGb = QGroupBox(self.centralwidget)
        self.selObjGb.setMinimumSize(QSize(0, 96))
        self.selObjGb.setMaximumSize(QSize(16777215, 220))
        self.selObjGb.setObjectName("selObjGb")
        self.verticalLayout_2 = QVBoxLayout(self.selObjGb)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.selList = QTextEdit(self.selObjGb)
        self.selList.setObjectName("selList")
        self.verticalLayout_2.addWidget(self.selList)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addSelListBt = QPushButton(self.selObjGb)
        self.addSelListBt.setObjectName("addSelListBt")
        self.horizontalLayout_2.addWidget(self.addSelListBt)
        self.clearSelListBt = QPushButton(self.selObjGb)
        self.clearSelListBt.setMaximumSize(QSize(56, 16777215))
        self.clearSelListBt.setObjectName("clearSelListBt")
        self.horizontalLayout_2.addWidget(self.clearSelListBt)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addWidget(self.selObjGb)
        self.horizontalLayout_4.setStretch(1, 1)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        self.horizontalLayout_6 = QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.saveBt = QPushButton(self.centralwidget)
        self.saveBt.setMinimumSize(QSize(0, 38))
        self.saveBt.setObjectName("saveBt")
        self.horizontalLayout_6.addWidget(self.saveBt)
        self.closeBt = QPushButton(self.centralwidget)
        self.closeBt.setMinimumSize(QSize(0, 38))
        self.closeBt.setObjectName("closeBt")
        self.horizontalLayout_6.addWidget(self.closeBt)
        self.gridLayout.addLayout(self.horizontalLayout_6, 6, 0, 1, 1)
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addBt = QPushButton(self.groupBox_3)
        self.addBt.setMinimumSize(QSize(0, 28))
        self.addBt.setObjectName("addBt")
        self.horizontalLayout.addWidget(self.addBt)
        self.importBt = QPushButton(self.groupBox_3)
        self.importBt.setMinimumSize(QSize(0, 28))
        self.importBt.setObjectName("importBt")
        self.horizontalLayout.addWidget(self.importBt)
        self.delBt = QPushButton(self.groupBox_3)
        self.delBt.setMinimumSize(QSize(0, 28))
        self.delBt.setObjectName("delBt")
        self.horizontalLayout.addWidget(self.delBt)
        self.gridLayout.addWidget(self.groupBox_3, 3, 0, 1, 1)
        self.gridLayout.setRowStretch(5, 1)
        self.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(self)
        self.menubar.setGeometry(QRect(0, 0, 465, 24))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(self)
        QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        self.groupBox_2.setTitle("BG_Image")
        self.bgImgBt.setText("...")
        self.groupBox.setTitle("Script of Button")
        self.msRb.setText("MaxScript")
        self.pyRb.setText("Python")
        self.testRunBt.setText("TestRun")
        self.btStats.setTitle("Button Setting")
        self.label_3.setText("Text")
        self.label_4.setText("X")
        self.label_5.setText("Y")
        self.label_6.setText("W")
        self.label_7.setText("H")
        self.colLbl.setText("ColorLbl")
        self.label_8.setText("alpha")
        self.selObjGb.setTitle("SelectList")
        self.addSelListBt.setText(u"選択を追加")
        self.clearSelListBt.setText(u"クリア")
        self.saveBt.setText("Save")
        self.closeBt.setText("Close")
        self.groupBox_3.setTitle("Create Button")
        self.addBt.setText(u"ボタン追加")
        self.importBt.setText(u"ボタン読み込み")
        self.delBt.setText(u"ボタン削除")
        self.menuMenu.setTitle("Menu")

