[SJ_Tools_all]
rcMenuFileMiStr =ファイル
rcMenuHelpMiStr =ヘルプ

MesseTitleInfoStr =お知らせ
MesseTitleWngStr =警告 
MesseTitleCtnStr =注意
MesseTitleErrStr =エラー
MesseTitleChkStr =確認

MesseCmnErrStr =失敗しました
MesseCmnChkStr =実行しますか?
MesseCmnFileErrStr ="読み込みに失敗しました\n未知の形式のファイルです"
MesseCmnProgStr =しばらくお待ちください

[SJ_Adjuster.ms]
SJ_AdjusterNameAndVersion =あじゃすた～

[SJ_AnimKey_Preview.ms]
SJ_AnimKey_PreviewNameAndVersion =あにき～

[SJ_Bio_Skin_Plus.ms]
SJ_Bio_Skin_PlusNameAndVersion =ばいきん +

[SJ_Bip_Fitter.ms]
SJ_Bip_FitterNameAndVersion =びっぱ～

[SJ_Hider.ms]
SJ_HiderNameAndVersion =はいだ～

[SJ_Key_Machine.ms]

[SJ_LayerLayer.ms]
SJ_LayerLayerNameAndVersion =れいや～いやぁ～
grpDelete =レイヤーを削除
uselessLayerDeleteBt =未使用を削除
allLayerDeleteBt =全て削除
grpStrings =文字列で整理
allLayerPfxBt =全レイヤー先頭に文字を追加
allLayerSfxBt =全レイヤー語尾に文字を追加
allLayerDlPxBt =対象文字を削除
layerDelByNameBt =名前でレイヤーを削除
grpPreset =レイヤープリセット
presetLbl =ダブルクリックで切り替えます

defaultNameStr =プリセット

MesseCapPSStr =プリセットを保存
MesseCapPLStr =プリセットを読み込み
MesseCapLSStr =レイヤーを保存
MesseCapLLStr =レイヤーを読み込み

MesseAStr ="本当に全てのレイヤーを削除しますか?\n（レイヤー内のオブジェクトは削除されません\n0レイヤーへ移動します）"
MesseBStr =テキストが入力されていません
MesseCStr = を削除しますか?

[SJ_PBake.ms]
SJ_PBakeNameAndVersion =ぴーべいく ぶらすとふぁいあ～

[SJ_Poser.ms]
SJ_PoserNameAndVersion =ぽーちゃん

[SJ_Renamer.ms]
SJ_RenamerNameAndVersion =りねーにゃー
similarSearchBt =近い名前を検索
toolTip =指定の文字列に近い名前のオブジェクトを検索します

[SJ_Roller.ms]
SJ_RollerNameAndVersion =くるくる～

[SJ_Scene_Slicer.ms]
SJ_Scene_SlicerNameAndVersion =すらいちゃん

[SJ_Selector.ms]
SJ_SelectorNameAndVersion =せれくにゃ～

[SJ_Selector_Rig.ms]
SJ_Selector_RigNameAndVersion =せれくにゃ～はりけ～ん

[SJ_Spark.ms]
SJ_SparkNameAndVersion =すぱーくん

[SJ_Time_Machine.ms]

[SJ_Attribute_Holder.ms]
SJ_Attribute_HolderNameAndVersion =あとりぶーとー

[SJ_Cut_Collector.ms]
SJ_Cut_CollectorNameAndVersion =かっとこれくたぁ～

